// Code generated by gotemplate. DO NOT EDIT.

package requests

// template type Template()

type (
	GetChain struct {
		ArgsGetChain
		RespGetChain
	}

	ArgsGetChain struct {
	}

	RespGetChain struct {
	}
)

func (t *GetChain) Args() interface{} {
	var args interface{} = &t.ArgsGetChain
	return args
}

func (t *GetChain) Resp() interface{} {
	var resp interface{} = &t.RespGetChain
	return resp
}
