// Code generated by gotemplate. DO NOT EDIT.

package requests

// template type Template()

type (
	GetChunkByHash struct {
		ArgsGetChunkByHash
		RespGetChunkByHash
	}

	ArgsGetChunkByHash struct {
	}

	RespGetChunkByHash struct {
	}
)

func (t *GetChunkByHash) Args() interface{} {
	var args interface{} = &t.ArgsGetChunkByHash
	return args
}

func (t *GetChunkByHash) Resp() interface{} {
	var resp interface{} = &t.RespGetChunkByHash
	return resp
}
