// Code generated by gotemplate. DO NOT EDIT.

package requests

// template type Template()

type (
	GetChainHead struct {
		ArgsGetChainHead
		RespGetChainHead
	}

	ArgsGetChainHead struct {
	}

	RespGetChainHead struct {
	}
)

func (t *GetChainHead) Args() interface{} {
	var args interface{} = &t.ArgsGetChainHead
	return args
}

func (t *GetChainHead) Resp() interface{} {
	var resp interface{} = &t.RespGetChainHead
	return resp
}
