// Code generated by gotemplate. DO NOT EDIT.

package requests

// template type Template()

type (
	NotifyBeginChunk struct {
		ArgsNotifyBeginChunk
		RespNotifyBeginChunk
	}

	ArgsNotifyBeginChunk struct {
	}

	RespNotifyBeginChunk struct {
	}
)

func (t *NotifyBeginChunk) Args() interface{} {
	var args interface{} = &t.ArgsNotifyBeginChunk
	return args
}

func (t *NotifyBeginChunk) Resp() interface{} {
	var resp interface{} = &t.RespNotifyBeginChunk
	return resp
}
