// Code generated by gotemplate. DO NOT EDIT.

package requests

// template type Template()

type (
	NotifyDoneBlock struct {
		ArgsNotifyDoneBlock
		RespNotifyDoneBlock
	}

	ArgsNotifyDoneBlock struct {
	}

	RespNotifyDoneBlock struct {
	}
)

func (t *NotifyDoneBlock) Args() interface{} {
	var args interface{} = &t.ArgsNotifyDoneBlock
	return args
}

func (t *NotifyDoneBlock) Resp() interface{} {
	var resp interface{} = &t.RespNotifyDoneBlock
	return resp
}
