// Code generated by gotemplate. DO NOT EDIT.

package requests

// template type Template()

type (
	NotifyDoneChunk struct {
		ArgsNotifyDoneChunk
		RespNotifyDoneChunk
	}

	ArgsNotifyDoneChunk struct {
	}

	RespNotifyDoneChunk struct {
	}
)

func (t *NotifyDoneChunk) Args() interface{} {
	var args interface{} = &t.ArgsNotifyDoneChunk
	return args
}

func (t *NotifyDoneChunk) Resp() interface{} {
	var resp interface{} = &t.RespNotifyDoneChunk
	return resp
}
