// Code generated by "stringer -type=MessageEnum"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotifyBeginChunk-1]
	_ = x[NotifyDoneChunk-2]
	_ = x[NotifyDoneBlock-3]
	_ = x[GetChain-4]
	_ = x[GetChainHead-5]
	_ = x[GetStateByHash-6]
	_ = x[GetChunkByHash-7]
	_ = x[Return-8]
}

const _MessageEnum_name = "NotifyBeginChunkNotifyDoneChunkNotifyDoneBlockGetChainGetChainHeadGetStateByHashGetChunkByHashReturn"

var _MessageEnum_index = [...]uint8{0, 16, 31, 46, 54, 66, 80, 94, 100}

func (i MessageEnum) String() string {
	i -= 1
	if i >= MessageEnum(len(_MessageEnum_index)-1) {
		return "MessageEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageEnum_name[_MessageEnum_index[i]:_MessageEnum_index[i+1]]
}
